spring:
  profiles:
    active: dev
  redis:
    host: 192.168.0.105
    port: 6379
    database: 1
    timeout: 5000

#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#  pattern:
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'